import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="flex items-center"> 
          <Image width={100} height={100} src="/banana.jpg" alt="Banana logo"/>
          <h1 className="mb-4 text-4xl font-bold tracking-tight"> 
          
          Next.js CRUD App 
          </h1> 
          </div> 
          <hr/> 
          <p>&nbsp;</p> 
        {children}
        <p>&nbsp;</p> 
        Created by Andrzej Gawłowski
        </body>
    </html>
  );
}
